set_property IOSTANDARD LVCMOS33 [get_ports {D0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {D1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {D2[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {D3[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {D4[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {D5[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {D6[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {D7[0]}]

set_property PACKAGE_PIN T22 [get_ports {D0[0]}]
set_property PACKAGE_PIN T21 [get_ports {D1[0]}]
set_property PACKAGE_PIN U22 [get_ports {D2[0]}]
set_property PACKAGE_PIN U21 [get_ports {D3[0]}]
set_property PACKAGE_PIN V22 [get_ports {D4[0]}]
set_property PACKAGE_PIN W22 [get_ports {D5[0]}]
set_property PACKAGE_PIN U19 [get_ports {D6[0]}]
set_property PACKAGE_PIN U14 [get_ports {D7[0]}]
